AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  lambdaJapaneseLearnNew:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.main.handler
      Runtime: python3.11
      CodeUri: .
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          DATABASE_URL: "mysql+pymysql://dbmasteruser:D%<WBLKR9!,ZNT1gNzxIU#*,D_xU?48q@ls-c473c9825c62e9efe33c74c6f241de905c9d5e8d.cxcecqy6s31q.ap-northeast-1.rds.amazonaws.com:3306/japanese_learn"
          S3_BUCKET_NAME: "bucket-japanese-learn-resource"
          AWS_REGION: "ap-northeast-1"
          GOOGLE_APPLICATION_CREDENTIALS: "google-tts-key.json"
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /api/v1/{proxy+}
            Method: any

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

  LambdaInvokePermissionNew:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt lambdaJapaneseLearnNew.Arn
      Principal: apigateway.amazonaws.com