AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  DatabaseUrl:
    Type: String
    Description: "Database connection URL"
    NoEcho: true
  S3BucketName:
    Type: String
    Description: "S3 bucket name for resources"
  GoogleApiKey:
    Type: String
    Description: "Google Custom Search API Key"
    NoEcho: true
  GoogleSearchEngineId:
    Type: String
    Description: "Google Custom Search Engine ID"
    NoEcho: true
  GeminiApiKey:
    Type: String
    Description: "Google Gemini API Key for AI descriptions"
    NoEcho: true

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 256
    Timeout: 30
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: japanese-learn
        LOG_LEVEL: INFO
        DATABASE_URL: !Ref DatabaseUrl
        S3_BUCKET_NAME: !Ref S3BucketName
        GOOGLE_APPLICATION_CREDENTIALS: google-tts-key.json
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin,Accept'"
      AllowOrigin: "'*'"

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub ${AWS::StackName}-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AuthSessionValidity: 15
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: "minutes"
        IdToken: "minutes"
        RefreshToken: "days"

  # DynamoDB Table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-table
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName

  # Lambda Functions
  WordsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/words
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-WordsFunction"
      CodeUri: ./app/api/v1/words
      Handler: app.lambda_handler
      Description: "Lambda function for words-related endpoints"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          S3_BUCKET_NAME: !Ref S3BucketName
          GOOGLE_APPLICATION_CREDENTIALS: google-tts-key.json
          DATABASE_URL: !Ref DatabaseUrl
          GOOGLE_API_KEY: !Ref GoogleApiKey
          GOOGLE_SEARCH_ENGINE_ID: !Ref GoogleSearchEngineId
          GEMINI_API_KEY: !Ref GeminiApiKey
      Events:
        WordsApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/words
            Method: ANY
        WordsApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/words/{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}"
              - !Sub "arn:aws:s3:::${S3BucketName}/*"

  LearnWordsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/learn_words
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-LearnWordsFunction"
      CodeUri: ./app/api/v1/learn_words
      Handler: app.lambda_handler
      Description: "Lambda function for learning history endpoints"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_APP_CLIENT_ID: !Ref UserPoolClient
          FRONTEND_URL: "https://nihongo.cloud"
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        LearnWordsApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/learn_words
            Method: ANY
        LearnWordsApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/learn_words/{proxy+}
            Method: ANY
        OAuthCallbackEvent:
          Type: Api
          Properties:
            Path: /api/v1/auth/oauth/callback
            Method: ANY
        OAuthGoogleEvent:
          Type: Api
          Properties:
            Path: /api/v1/auth/oauth/google
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  UsersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/users
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-UsersFunction"
      CodeUri: ./app/api/v1/users
      Handler: app.lambda_handler
      Description: "Lambda function for user progress and plan endpoints"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_APP_CLIENT_ID: !Ref UserPoolClient
          FRONTEND_URL: "https://nihongo.cloud"
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        UsersApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/users
            Method: ANY
        UsersApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/users/{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  KanjisFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/kanjis
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-KanjisFunction"
      CodeUri: ./app/api/v1/kanjis
      Handler: app.lambda_handler
      Description: "Lambda function for kanjis-related endpoints"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        KanjisApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/kanjis
            Method: ANY
        KanjisApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/kanjis/{proxy+}
            Method: ANY
        ComponentsApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/components
            Method: ANY
        ComponentsApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/components/{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
          - Effect: Allow
            Action:
                - dynamodb:Query
                - dynamodb:Scan
            Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/*"

  SearchFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/search
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SearchFunction"
      CodeUri: ./app/api/v1/search
      Handler: app.lambda_handler
      Description: "統合検索機能（単語、漢字、例文検索）"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        SearchApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/search
            Method: ANY
        SearchApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/search/{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
          - Effect: Allow
            Action:
                - dynamodb:Query
                - dynamodb:Scan
            Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/name-index"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/english-index"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/vietnamese-index"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/character-index"

  SentencesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/sentences
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SentencesFunction"
      CodeUri: ./app/api/v1/sentences
      Handler: app.lambda_handler
      Description: "Lambda function for sentences-related endpoints"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          S3_BUCKET_NAME: !Ref S3BucketName
          GOOGLE_APPLICATION_CREDENTIALS: google-tts-key.json
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        SentencesApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/sentences
            Method: ANY
        SentencesApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/sentences/{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}"
              - !Sub "arn:aws:s3:::${S3BucketName}/*"

  SentenceCompositionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        UseContainer: true
        ProjectPath: ./app/api/v1/sentence_composition
        InstallDependencies: true
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SentenceCompositionFunction"
      CodeUri: ./app/api/v1/sentence_composition
      Handler: app.lambda_handler
      Description: "Lambda function for sentence composition quiz endpoints"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        QuizzesApiRootEvent:
          Type: Api
          Properties:
            Path: /api/v1/quizzes
            Method: ANY
        QuizzesApiProxyEvent:
          Type: Api
          Properties:
            Path: /api/v1/quizzes/{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
          - Effect: Allow
            Action:
                - dynamodb:Query
                - dynamodb:Scan
            Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/index/*"

  # CloudWatch Log Groups
  WordsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${WordsFunction}"
      RetentionInDays: 14
    DependsOn: WordsFunction

  KanjisFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KanjisFunction}"
      RetentionInDays: 14
    DependsOn: KanjisFunction

  LearnWordsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LearnWordsFunction}"
      RetentionInDays: 14
    DependsOn: LearnWordsFunction

  UsersFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${UsersFunction}"
      RetentionInDays: 14
    DependsOn: UsersFunction

  SearchFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SearchFunction}"
      RetentionInDays: 14
    DependsOn: SearchFunction

  SentencesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SentencesFunction}"
      RetentionInDays: 14
    DependsOn: SentencesFunction

  SentenceCompositionFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SentenceCompositionFunction}"
      RetentionInDays: 14
    DependsOn: SentenceCompositionFunction

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WordsFunctionArn:
    Description: "Words Function ARN"
    Value: !GetAtt WordsFunction.Arn
  KanjisFunctionArn:
    Description: "Kanjis Function ARN"
    Value: !GetAtt KanjisFunction.Arn
  SearchFunctionArn:
    Description: "Search Function ARN"
    Value: !GetAtt SearchFunction.Arn
  SentencesFunctionArn:
    Description: "Sentences Function ARN"
    Value: !GetAtt SentencesFunction.Arn
  SentenceCompositionFunctionArn:
    Description: "Sentence Composition Function ARN"
    Value: !GetAtt SentenceCompositionFunction.Arn
  ApiId:
    Description: "API Gateway ID"
    Value: !Ref ServerlessRestApi
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient
