"""create kanjis table

Revision ID: 05682287be08
Revises: 9c0986e5bde5
Create Date: 2025-01-15 00:24:29.963562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05682287be08'
down_revision: Union[str, None] = '9c0986e5bde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanjis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('character', sa.String(length=255), nullable=False),
        sa.Column('english', sa.String(length=255), nullable=True),
        sa.Column('vietnamese', sa.String(length=255), nullable=True),
        sa.Column('strokes', sa.Integer(), nullable=True),
        sa.Column('onyomi', sa.String(length=255), nullable=True),
        sa.Column('kunyomi', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kanjis')
    # ### end Alembic commands ###
