"""Create words table

Revision ID: d98aaa956862
Revises: 
Create Date: 2025-01-04 19:31:13.457975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd98aaa956862'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hiragana', sa.String(length=255), nullable=False),
    sa.Column('romanian', sa.String(length=255), nullable=True),
    sa.Column('is_katakana', sa.Boolean(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('english', sa.String(length=255), nullable=True),
    sa.Column('vietnamese', sa.String(length=255), nullable=True),
    sa.Column('lexical_category', sa.String(length=50), nullable=True),
    sa.Column('accent_up', sa.Integer(), nullable=True),
    sa.Column('accent_down', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
